apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateadx-deployment
  labels:
    app: updateadx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: updateadx-app
  template:
    metadata:
      labels:
        app: updateadx-app
    spec:
      containers:
      - name: updateadx-app
        image: sudha2022\updateadx:V2
        ports:
        - containerPort: 80
